eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

mybatis:
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://10.168.0.3:3306/log_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

server:
  port: 8888

logging:
  config: classpath:logback-logstash.xml
